# Generated by Django 5.1.3 on 2024-11-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ammount', models.IntegerField()),
                ('intrest_rate', models.IntegerField()),
                ('purpose', models.CharField(max_length=250)),
                ('client_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_APP.client')),
            ],
        ),
    ]
