# Generated by Django 5.1.3 on 2024-11-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='intrest_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='CNIC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.CharField(default='6 Months', max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='employment_status',
            field=models.CharField(default='Unemployed', max_length=100),
        ),
        migrations.AddField(
            model_name='loan',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Cnic/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='intrest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='martrial_status',
            field=models.CharField(default='Single', max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='organization_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Ammount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(default='General', max_length=250),
        ),
    ]
