# Generated by Django 5.1.3 on 2024-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_APP', '0006_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_holder',
            field=models.BooleanField(default=False),
        ),
    ]
